collision_objects:
  - id: "Table" 
    frame_id: "panda_link0"
    shape_type: 1
    dimension: [0.8, 0.8, 0.01]
    primitive_poses: [0.6, 0.0, 0.0]
    primitive_orientation: [0.0, 0.0, 0.0]
  - id: "C3" 
    frame_id: "panda_link0"
    shape_type: 1
    dimension: [0.02, 0.02, 0.2]
    primitive_poses: [0.5, 0.0, 0.5]
    primitive_orientation: [0.0, 0.0, 0.0]
  - id: "C4" 
    frame_id: "panda_link0"
    shape_type: 3
    dimension: [0.2, 0.02]
    primitive_poses: [0.75, 0.2, 0.0]
    primitive_orientation: [0.0, 0.0, 0.0]
  - id: "C2" 
    frame_id: "panda_link0"
    shape_type: 3
    dimension: [0.2, 0.02]
    primitive_poses: [0.7, -0.05, 0.0]
    primitive_orientation: [0.0, 0.0, 0.0]
  - id: "C1" 
    frame_id: "panda_link0"
    shape_type: 3
    dimension: [0.2, 0.02]
    primitive_poses: [0.5, -0.15, 0.0]
    primitive_orientation: [0.0, 0.0, 0.0]
  - id: "C0" 
    frame_id: "panda_link0"
    shape_type: 3
    dimension: [0.2, 0.02]
    primitive_poses: [0.6, 0.15, 0.0]
    primitive_orientation: [0.0, 0.0, 0.0]